### ISSUE TITLE
Overseer

### ISSUE THREAD

**Issue by Kevin-Mortimer-19** [Kevin-Mortimer-19/SSJ_24#7]
Overseer dialogue + overworld sprite

**Comment by Chrid420** [comment]
Writing dialogue for Overseer.

**Comment by Chrid420** [comment]
https://docs.google.com/spreadsheets/d/1VyVxtICUPgz56ogBKzfc20_cHimkcK2uHcZKdR5fdiw/edit?usp=sharing

**Comment by Kevin-Mortimer-19** [comment]
Can be marked as complete when the dialogue portraits display properly.
