### ISSUE TITLE
Shotgun dialogue

### ISSUE THREAD

**Issue by Kevin-Mortimer-19** [Kevin-Mortimer-19/SSJ_24#8]
Dialogue when you first retrieve the shotgun

**Comment by Chrid420** [comment]
I can create a small write up of some dialogue. Cannot implement it tho

**Comment by Chrid420** [comment]
Writing up Dialogue for Shotgun and all other NPCs + Overseer and even a narrator.

**Comment by Chrid420** [comment]
https://docs.google.com/spreadsheets/d/1VyVxtICUPgz56ogBKzfc20_cHimkcK2uHcZKdR5fdiw/edit?usp=sharing

**Comment by Kevin-Mortimer-19** [comment]
Can be marked as complete once the shotgun dialogue portrait is implemented.
